/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Sat Oct 28 15:43:42 IST 2023
 * 
 */

/* Generation options: */
#ifndef __mkUART_32bit_h__
#define __mkUART_32bit_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkUART_32bit module */
class MOD_mkUART_32bit : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_bit_cnt;
  MOD_Reg<tUInt32> INST_num_reg;
  MOD_Reg<tUInt8> INST_parity;
  MOD_Reg<tUInt8> INST_s_cnt;
  MOD_Reg<tUInt8> INST_sbuf;
  MOD_Wire<tUInt8> INST_sbuf_din;
  MOD_Reg<tUInt8> INST_tx;
  MOD_Wire<tUInt8> INST_tx_frag;
  MOD_Reg<tUInt8> INST_tx_line;
 
 /* Constructor */
 public:
  MOD_mkUART_32bit(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_par_in;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_par_in;
  tUInt8 DEF_NOT_tx_4___d59;
  tUInt8 DEF_tx___d34;
 
 /* Local definitions */
 private:
  tUInt8 DEF_x__h1010;
  tUInt8 DEF_x__h1005;
  tUInt8 DEF_s_cnt_EQ_3___d5;
  tUInt8 DEF_bit_cnt_5_EQ_10___d38;
  tUInt8 DEF_bit_cnt_5_EQ_9___d36;
 
 /* Rules */
 public:
  void RL_tx_8bit();
  void RL_update_sbuf();
  void RL_update_cnt();
  void RL_shift_out();
 
 /* Methods */
 public:
  void METH_par_in(tUInt32 ARG_par_in_par_input);
  tUInt8 METH_RDY_par_in();
  void METH_start_tx();
  tUInt8 METH_RDY_start_tx();
  tUInt8 METH_uart32bit_tx();
  tUInt8 METH_RDY_uart32bit_tx();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkUART_32bit &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkUART_32bit &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkUART_32bit &backing);
};

#endif /* ifndef __mkUART_32bit_h__ */
